import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { getSession } from '../lib/get-session';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import { useEffect, useState } from 'react';

export const getServerSideProps: GetServerSideProps<{
  views: number;
}> = async ({ req, res }) => {
  const session = await getSession(req, res);
  session.views = session.views ? session.views + 1 : 1;
  return {
    props: {
      views: session.views
    }
  };
};

export default function Home({
  views
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const [session, setSession] = useState(null);

  const fetchSession = async () => {
    const res = await fetch('/api/sessions');
    const data = await res.json();
    setSession(data);
  };

  useEffect(() => {
    fetchSession();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1>You have viewed this page {views} times.</h1>
        <h2>Session Data</h2>
        <pre>{JSON.stringify(session, null, 2)}</pre>
      </main>
    </>
  );
}
